config/routes.rb
Mobility::Application.routes.draw do
  resources :mbb_product_data_usages

  resources :institution_populations

  resources :institutions

  resources :mbb_institution_abbreviations

  resources :institution_categories

  resources :mbb_connections_stagings

  resources :mbb_products

  resources :mbb_channels

  resources :mbb_seasons

  get "reports/index"

  get "reports/bobadas"

  get "reports/connections_month"

  get "reports/historicals_seasons"

  resources :mbb_connections

  root :to => 'reports#index'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  belongs_to :institution_category

  has_many :institution_populations
  has_many :mbb_institution_abbreviations
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutions }
    end
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.json
  def new
    load_auxiliary_data
    @institution = Institution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/1/edit
  def edit
    load_auxiliary_data
    @institution = Institution.find(params[:id])
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(params[:institution])

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render json: @institution, status: :created, location: @institution }
      else
        format.html { render action: "new" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.json
  def update
    @institution = Institution.find(params[:id])

    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end

  private
  def load_auxiliary_data
    @institution_categories = InstitutionCategory.find(:all, :order => "name")
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :institution_category_id %><br />
    <%= f.collection_select :institution_category_id, @institution_categories,
                            :id, :name,
                            :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Listing institutions</h1>

<table>
  <tr>
    <th>Abbreviation</th>
    <th>Name</th>
    <th>Institution category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @institutions.each do |institution| %>
  <tr>
    <td><%= institution.abbreviation %></td>
    <td><%= institution.name %></td>
    <td><%= institution.institution_category.name %></td>
    <td><%= link_to 'Show', institution %></td>
    <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
    <td><%= link_to 'Destroy', institution, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Abbreviation:</b>
  <%= @institution.abbreviation %>
</p>

<p>
  <b>Name:</b>
  <%= @institution.name %>
</p>

<p>
  <b>Institution category:</b>
  <%= @institution.institution_category.name %>
</p>


<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>