config/routes.rb
Mobility::Application.routes.draw do
  resources :mbb_product_data_usages

  resources :institution_populations

  resources :institutions

  resources :mbb_institution_abbreviations

  resources :institution_categories

  resources :mbb_connections_stagings

  resources :mbb_products

  resources :mbb_channels

  resources :mbb_seasons

  get "reports/index"

  get "reports/bobadas"

  get "reports/connections_month"

  get "reports/historicals_seasons"

  resources :mbb_connections

  root :to => 'reports#index'

end

app/models/mbb_channel.rb
class MbbChannel < ActiveRecord::Base
end

app/controllers/mbb_channels_controller.rb
class MbbChannelsController < ApplicationController
  # GET /mbb_channels
  # GET /mbb_channels.json
  def index
    @mbb_channels = MbbChannel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mbb_channels }
    end
  end

  # GET /mbb_channels/1
  # GET /mbb_channels/1.json
  def show
    @mbb_channel = MbbChannel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mbb_channel }
    end
  end

  # GET /mbb_channels/new
  # GET /mbb_channels/new.json
  def new
    @mbb_channel = MbbChannel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mbb_channel }
    end
  end

  # GET /mbb_channels/1/edit
  def edit
    @mbb_channel = MbbChannel.find(params[:id])
  end

  # POST /mbb_channels
  # POST /mbb_channels.json
  def create
    @mbb_channel = MbbChannel.new(params[:mbb_channel])

    respond_to do |format|
      if @mbb_channel.save
        format.html { redirect_to @mbb_channel, notice: 'Mbb channel was successfully created.' }
        format.json { render json: @mbb_channel, status: :created, location: @mbb_channel }
      else
        format.html { render action: "new" }
        format.json { render json: @mbb_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mbb_channels/1
  # PUT /mbb_channels/1.json
  def update
    @mbb_channel = MbbChannel.find(params[:id])

    respond_to do |format|
      if @mbb_channel.update_attributes(params[:mbb_channel])
        format.html { redirect_to @mbb_channel, notice: 'Mbb channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mbb_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mbb_channels/1
  # DELETE /mbb_channels/1.json
  def destroy
    @mbb_channel = MbbChannel.find(params[:id])
    @mbb_channel.destroy

    respond_to do |format|
      format.html { redirect_to mbb_channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mbb_channels_helper.rb
module MbbChannelsHelper
end

app/views/mbb_channels/_form.html.erb
<%= form_for(@mbb_channel) do |f| %>
  <% if @mbb_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mbb_channel.errors.count, "error") %> prohibited this mbb_channel from being saved:</h2>

      <ul>
      <% @mbb_channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mbb_channels/edit.html.erb
<h1>Editing mbb_channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @mbb_channel %> |
<%= link_to 'Back', mbb_channels_path %>

app/views/mbb_channels/index.html.erb
<h1>Listing mbb_channels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mbb_channels.each do |mbb_channel| %>
  <tr>
    <td><%= mbb_channel.name %></td>
    <td><%= mbb_channel.description %></td>
    <td><%= link_to 'Show', mbb_channel %></td>
    <td><%= link_to 'Edit', edit_mbb_channel_path(mbb_channel) %></td>
    <td><%= link_to 'Destroy', mbb_channel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mbb channel', new_mbb_channel_path %>

app/views/mbb_channels/new.html.erb
<h1>New mbb_channel</h1>

<%= render 'form' %>

<%= link_to 'Back', mbb_channels_path %>

app/views/mbb_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mbb_channel.name %>
</p>
<p>
  <b>Description:</b>
  <%= @mbb_channel.description %>
</p>


<%= link_to 'Edit', edit_mbb_channel_path(@mbb_channel) %> |
<%= link_to 'Back', mbb_channels_path %>