config/routes.rb
Mobility::Application.routes.draw do
  resources :mbb_product_data_usages

  resources :institution_populations

  resources :institutions

  resources :mbb_institution_abbreviations

  resources :institution_categories

  resources :mbb_connections_stagings

  resources :mbb_products

  resources :mbb_channels

  resources :mbb_seasons

  get "reports/index"

  get "reports/bobadas"

  get "reports/connections_month"

  get "reports/historicals_seasons"

  resources :mbb_connections

  root :to => 'reports#index'

end

app/models/mbb_season.rb
class MbbSeason < ActiveRecord::Base
end

app/controllers/mbb_seasons_controller.rb
class MbbSeasonsController < ApplicationController
  # GET /mbb_seasons
  # GET /mbb_seasons.json
  def index
    @mbb_seasons = MbbSeason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mbb_seasons }
    end
  end

  # GET /mbb_seasons/1
  # GET /mbb_seasons/1.json
  def show
    @mbb_season = MbbSeason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mbb_season }
    end
  end

  # GET /mbb_seasons/new
  # GET /mbb_seasons/new.json
  def new
    @mbb_season = MbbSeason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mbb_season }
    end
  end

  # GET /mbb_seasons/1/edit
  def edit
    @mbb_season = MbbSeason.find(params[:id])
  end

  # POST /mbb_seasons
  # POST /mbb_seasons.json
  def create
    @mbb_season = MbbSeason.new(params[:mbb_season])

    respond_to do |format|
      if @mbb_season.save
        format.html { redirect_to @mbb_season, notice: 'Mbb season was successfully created.' }
        format.json { render json: @mbb_season, status: :created, location: @mbb_season }
      else
        format.html { render action: "new" }
        format.json { render json: @mbb_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mbb_seasons/1
  # PUT /mbb_seasons/1.json
  def update
    @mbb_season = MbbSeason.find(params[:id])

    respond_to do |format|
      if @mbb_season.update_attributes(params[:mbb_season])
        format.html { redirect_to @mbb_season, notice: 'Mbb season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mbb_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mbb_seasons/1
  # DELETE /mbb_seasons/1.json
  def destroy
    @mbb_season = MbbSeason.find(params[:id])
    @mbb_season.destroy

    respond_to do |format|
      format.html { redirect_to mbb_seasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mbb_seasons_helper.rb
module MbbSeasonsHelper
end

app/views/mbb_seasons/_form.html.erb
<%= form_for(@mbb_season) do |f| %>
  <% if @mbb_season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mbb_season.errors.count, "error") %> prohibited this mbb_season from being saved:</h2>

      <ul>
      <% @mbb_season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :season_begin %><br />
    <%= f.text_field :season_begin %>
  </div>
  <div class="field">
    <%= f.label :season_end %><br />
    <%= f.text_field :season_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mbb_seasons/edit.html.erb
<h1>Editing mbb_season</h1>

<%= render 'form' %>

<%= link_to 'Show', @mbb_season %> |
<%= link_to 'Back', mbb_seasons_path %>

app/views/mbb_seasons/index.html.erb
<h1>Listing mbb_seasons</h1>

<table>
  <tr>
    <th>Season begin</th>
    <th>Season end</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mbb_seasons.each do |mbb_season| %>
  <tr>
    <td><%= mbb_season.season_begin %></td>
    <td><%= mbb_season.season_end %></td>
    <td><%= link_to 'Show', mbb_season %></td>
    <td><%= link_to 'Edit', edit_mbb_season_path(mbb_season) %></td>
    <td><%= link_to 'Destroy', mbb_season, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mbb season', new_mbb_season_path %>

app/views/mbb_seasons/new.html.erb
<h1>New mbb_season</h1>

<%= render 'form' %>

<%= link_to 'Back', mbb_seasons_path %>

app/views/mbb_seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Season begin:</b>
  <%= @mbb_season.season_begin %>
</p>

<p>
  <b>Season end:</b>
  <%= @mbb_season.season_end %>
</p>


<%= link_to 'Edit', edit_mbb_season_path(@mbb_season) %> |
<%= link_to 'Back', mbb_seasons_path %>